### ISSUE TITLE
Container Run Issue

### ISSUE THREAD

**Issue by salihoglu87** [neezgee/apache_exporter#21]
Hello,
after building a "go" binary i suceeded to build also a docker image. But as i wanted to run the container i recieved this message:  
"docker: Error response from daemon: Container command '/apache_exporter' not found or does not exist".

**Comment by kanga333** [comment]
Hi. I also encountered the same problem when trying to run Docker along the README.
Normally, when go is built in a Linux environment such as Ubuntu, a binary linked to glibc is created.

```console
# ldd apache_exporter 
    linux-vdso.so.1 =>  (0x00007ffe1b728000)
    libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fd5d3798000)
    libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fd5d33ce000)
    /lib64/ld-linux-x86-64.so.2 (0x000055d0978e2000)
```

However, since alpine uses musl instead of glibc, it does not work if you just moved the binary. If you just need to run apache_exporter, it is easiest to use golang:alpine docker image.
If you need a lightweight DockerImage, it is easy to use a multi-stage build as below, but you can not build it unless the Docker version is 17.05 or later.
<https://docs.docker.com/engine/userguide/eng-image/multistage-build/>
In any case, because there are cases where it does not work well with the method of README, I will send a pull request to fix the problem.
